---
- name: add repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
- name: add APT repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ dist }}-pgdg main' state=present
- name: install PostgreSQL and related packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2
- name: create users
  become_user: postgres
  postgresql_user:
    name: "{{ item.owner }}"
    password: "{{ item.password | default(item.owner) }}"
    encrypted: yes
  with_items: 
  - "{{ databases }}"

- name: create databases 
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner | default('app') }}"
  with_items: 
  - "{{ databases }}"

- name: create extensions
  become_user: postgres
  postgresql_ext:
    name: "{{ item.1 }}"
    db: "{{ item.0.name }}"
  with_subelements: 
  - "{{ databases }}"
  - extensions
  - skip_missing: True
